package editor

import (
	"context"
	"fmt"
	"math/rand"
	"strings"
	"time"

	"github.com/Kyanite/noise/internal/app"
	"github.com/Kyanite/noise/internal/constants"
	"github.com/Kyanite/noise/internal/data"
	"github.com/Kyanite/noise/internal/theme"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
)

// chordPickerModel handles the chord picker UI component
type chordPickerModel struct {
	width        int
	height       int
	visible      bool
	progressions []data.ChordProgression
	filteredProg []data.ChordProgression
	selectedIdx  int
	activeMood   string
	showAll      bool
	loaded       bool
	aiService    *app.AIService
	isAIActive   bool
	customMood   string

	// Callback to insert chords into editor
	insertCallback func(chords []string)

	// Animation for visual feedback
	animationTime time.Time
	pulseProgress float64

	// Styles
	containerStyle   lipgloss.Style
	headerStyle      lipgloss.Style
	selectedStyle    lipgloss.Style
	normalStyle      lipgloss.Style
	moodStyle        lipgloss.Style
	descriptionStyle lipgloss.Style
	instructionStyle lipgloss.Style
}

// NewChordPickerModel creates a new chord picker model
func NewChordPickerModel(aiService *app.AIService) *chordPickerModel {
	t := theme.GetManager().Current()
	return &chordPickerModel{
		visible:       false,
		selectedIdx:   0,
		activeMood:    "all",
		showAll:       true,
		loaded:        false,
		aiService:     aiService,
		animationTime: time.Now(),

		containerStyle: lipgloss.NewStyle().
			Border(lipgloss.RoundedBorder()).
			BorderForeground(t.Primary).
			Background(t.Background).
			Padding(1, 2),

		headerStyle: lipgloss.NewStyle().
			Bold(true).
			Foreground(t.Primary).
			Align(lipgloss.Center).
			MarginBottom(1),

		selectedStyle: lipgloss.NewStyle().
			Background(t.Primary).
			Foreground(t.Background).
			Bold(true).
			Padding(0, 1),

		normalStyle: lipgloss.NewStyle().
			Foreground(t.Text).
			Padding(0, 1),

		moodStyle: lipgloss.NewStyle().
			Foreground(t.Accent).
			Bold(true).
			Padding(0, 1),

		descriptionStyle: lipgloss.NewStyle().
			Foreground(t.Secondary).
			Italic(true).
			MarginLeft(2),

		instructionStyle: lipgloss.NewStyle().
			Foreground(t.Secondary).
			Align(lipgloss.Center).
			MarginTop(1),
	}
}

// AIProgressionFoundMsg is sent when the AI finds new chord progressions
type AIProgressionFoundMsg struct {
	Progressions []string
	Mood         string
}

func (m *chordPickerModel) triggerAIBrainstorm() tea.Cmd {
	return func() tea.Msg {
		if m.aiService == nil {
			return nil
		}

		mood := m.activeMood
		if mood == "all" {
			mood = "inspirational"
		}

		ctx, cancel := context.WithTimeout(context.Background(), constants.ShortContextTimeout)
		defer cancel()

		suggestions, err := m.aiService.GenerateHarmonySuggestions(ctx, mood)
		if err != nil {
			return nil
		}

		return AIProgressionFoundMsg{
			Progressions: suggestions,
			Mood:         mood,
		}
	}
}

func (m *chordPickerModel) Init() tea.Cmd {
	return nil
}

// Update handles messages for the chord picker
func (m *chordPickerModel) Update(msg tea.Msg) (*chordPickerModel, tea.Cmd) {
	switch msg := msg.(type) {
	case AIProgressionFoundMsg:
		m.isAIActive = false
		// Convert strings to ChordProgression and prepend to filtered
		for i, prog := range msg.Progressions {
			chords := strings.Split(prog, " - ")
			m.filteredProg = append([]data.ChordProgression{{
				ID:          fmt.Sprintf("ai-%d-%d", i, time.Now().Unix()),
				Name:        "AI suggestion",
				Mood:        msg.Mood,
				Chords:      chords,
				Description: "Generated by harmony AI",
			}}, m.filteredProg...)
		}
		// Reset cursor to top suggestion
		m.selectedIdx = 0
		return m, nil

	case tea.WindowSizeMsg:
		m.width = msg.Width
		m.height = msg.Height

	case ShowChordPickerMsg:
		m.visible = true
		m.insertCallback = msg.InsertCallback
		m.selectedIdx = 0
		m.activeMood = "all"
		m.showAll = true
		m.animationTime = time.Now()

		// Load progressions if not already loaded
		if !m.loaded {
			if progressions, err := data.GetAllChordProgressions(); err == nil {
				m.progressions = progressions
				m.filteredProg = progressions
				m.loaded = true
			}
		}

		return m, nil

	case HideChordPickerMsg:
		m.visible = false
		return m, nil

	case tea.KeyMsg:
		if !m.visible {
			return m, nil
		}

		switch msg.String() {
		case "esc":
			m.visible = false
			return m, nil

		case "up", "k":
			if m.selectedIdx > 0 {
				m.selectedIdx--
			}

		case "down", "j":
			if m.selectedIdx < len(m.filteredProg)-1 {
				m.selectedIdx++
			}

		case "alt+a":
			// Trigger AI Brainstorm (for now just use activeMood if it's not 'all')
			if m.aiService != nil {
				return m, m.triggerAIBrainstorm()
			}

		case "1", "2", "3", "4":
			// Mood selection
			moods := []string{"all", "happy", "sad", "tense", "chill"}
			idx := 0
			switch msg.String() {
			case "1":
				idx = 0
			case "2":
				idx = 1
			case "3":
				idx = 2
			case "4":
				idx = 3
			}

			if idx < len(moods) {
				m.setMoodFilter(moods[idx])
			}

		case "alt+r":
			// Random selection
			if len(m.filteredProg) > 0 {
				m.selectedIdx = rand.Intn(len(m.filteredProg))
				m.animationTime = time.Now()
			}

		case "enter", " ":
			// Select and insert chords
			if m.selectedIdx >= 0 && m.selectedIdx < len(m.filteredProg) {
				selected := m.filteredProg[m.selectedIdx]
				if m.insertCallback != nil {
					m.insertCallback(selected.Chords)
				}
				m.visible = false
			}
		}
	}

	return m, nil
}

// View renders the chord picker
func (m *chordPickerModel) View() string {
	if !m.visible || !m.loaded {
		return ""
	}

	// Calculate dimensions
	maxWidth := m.width - 10
	if maxWidth < 60 {
		maxWidth = 60
	}

	maxHeight := m.height - 10
	if maxHeight < 20 {
		maxHeight = 20
	}

	// Build content
	var content strings.Builder

	// Header
	header := m.headerStyle.Render("[~] Quick Chord Picker")
	content.WriteString(header)
	content.WriteString("\n\n")

	// Mood filter
	content.WriteString(m.renderMoodFilter())
	content.WriteString("\n\n")

	// Progressions list
	content.WriteString(m.renderProgressionsList(maxWidth, maxHeight-8))

	// Instructions
	content.WriteString("\n\n")
	content.WriteString(m.renderInstructions())

	// Apply container style
	return m.containerStyle.Width(maxWidth).Render(content.String())
}

// renderMoodFilter renders the mood filter buttons
func (m *chordPickerModel) renderMoodFilter() string {
	t := theme.GetManager().Current()
	moods := []string{"all", "happy", "sad", "tense", "chill"}
	var buttons []string

	for i, mood := range moods {
		var style lipgloss.Style
		if mood == m.activeMood {
			style = m.moodStyle.Background(t.Primary).Foreground(t.Background)
		} else {
			style = m.moodStyle
		}

		button := style.Render(fmt.Sprintf("[%d] %s", i+1, strings.Title(mood)))
		buttons = append(buttons, button)
	}

	return strings.Join(buttons, " ")
}

// renderProgressionsList renders the list of chord progressions
func (m *chordPickerModel) renderProgressionsList(maxWidth, maxHeight int) string {
	if len(m.filteredProg) == 0 {
		return "No progressions found for this mood."
	}

	var lines []string

	// Calculate visible items
	visibleItems := maxHeight
	if visibleItems > len(m.filteredProg) {
		visibleItems = len(m.filteredProg)
	}

	// Calculate scroll position
	startIdx := m.selectedIdx
	if startIdx+visibleItems > len(m.filteredProg) {
		startIdx = len(m.filteredProg) - visibleItems
	}
	if startIdx < 0 {
		startIdx = 0
	}

	// Render visible items
	for i := startIdx; i < startIdx+visibleItems && i < len(m.filteredProg); i++ {
		progression := m.filteredProg[i]

		var style lipgloss.Style
		if i == m.selectedIdx {
			style = m.selectedStyle
		} else {
			style = m.normalStyle
		}

		// Format: [index] Name - Chords
		chordStr := strings.Join(progression.Chords, " - ")
		lineText := fmt.Sprintf("%d. %s - %s", i+1, progression.Name, chordStr)

		// Truncate if too long
		if len(lineText) > maxWidth-4 {
			lineText = lineText[:maxWidth-7] + "..."
		}

		line := style.Render(lineText)
		lines = append(lines, line)

		// Add description for selected item
		if i == m.selectedIdx {
			desc := m.descriptionStyle.Render(progression.Description)
			lines = append(lines, desc)
		}
	}

	return strings.Join(lines, "\n")
}

// renderInstructions renders the instruction text
func (m *chordPickerModel) renderInstructions() string {
	instructions := []string{
		"[1-5] Filter by mood",
		"[Alt+R] Random selection",
		"[Alt+A] AI Brainstorm",
		"[UpDown] Navigate",
		"[Enter/Space] Insert chords",
		"[Esc] Cancel",
	}

	return m.instructionStyle.Render(strings.Join(instructions, " | "))
}

// setMoodFilter sets the mood filter and updates the filtered progressions
func (m *chordPickerModel) setMoodFilter(mood string) {
	m.activeMood = mood
	m.showAll = (mood == "all")
	m.selectedIdx = 0

	if m.showAll {
		m.filteredProg = m.progressions
	} else {
		var filtered []data.ChordProgression
		for _, prog := range m.progressions {
			if prog.Mood == mood {
				filtered = append(filtered, prog)
			}
		}
		m.filteredProg = filtered
	}
}

// Show shows the chord picker with the given callback
func (m *chordPickerModel) Show(callback func(chords []string)) tea.Cmd {
	return func() tea.Msg {
		return ShowChordPickerMsg{InsertCallback: callback}
	}
}

// Hide hides the chord picker
func (m *chordPickerModel) Hide() tea.Cmd {
	return func() tea.Msg {
		return HideChordPickerMsg{}
	}
}

// IsVisible returns whether the chord picker is currently visible
func (m *chordPickerModel) IsVisible() bool {
	return m.visible
}

// GetSelectedProgression returns the currently selected progression
func (m *chordPickerModel) GetSelectedProgression() *data.ChordProgression {
	if m.selectedIdx >= 0 && m.selectedIdx < len(m.filteredProg) {
		return &m.filteredProg[m.selectedIdx]
	}
	return nil
}

// ShowChordPickerMsg requests display of the chord picker.
type ShowChordPickerMsg struct {
	InsertCallback func(chords []string)
}

type HideChordPickerMsg struct{}
